// Copyright (c) PdfToSvg.NET contributors.
// https://github.com/dmester/pdftosvg.net
// Licensed under the MIT License.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PdfToSvg.SourceGenerators.Names
{
    /// <summary>
    /// This generator adds a lookup method to the "Names" class for interning common names for lower memory usage.
    /// </summary>
    [Generator]
    public class NamesGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    (syntaxNode, _) =>
                        syntaxNode is ClassDeclarationSyntax classDeclaration &&
                        classDeclaration.Identifier.Text == "Names" &&
                        classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)) &&
                        classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
                    (context, _) =>
                        context.SemanticModel.GetDeclaredSymbol(context.Node) as INamedTypeSymbol)
                .Where(symbol => symbol is not null);

            var compilationAndClasses = context.CompilationProvider.Combine(classes.Collect());

            context.RegisterSourceOutput(
                compilationAndClasses,
                (spc, source) => Generate(spc, source.Left, source.Right!));
        }

        private static List<(string PropertyName, LiteralExpressionSyntax Value)> GetNames(Compilation compilation, INamedTypeSymbol classSymbol)
        {
            var result = new List<(string PropertyName, LiteralExpressionSyntax Value)>();

            var properties = classSymbol
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Where(property => property.Type.Name == "PdfName");

            foreach (var property in properties)
            {
                // Expected syntax of initialization:
                //
                // ```
                // public static PdfName WinAnsiEncoding { get; } = new PdfName("WinAnsiEncoding");
                // ```
                //
                var syntaxRef = property.DeclaringSyntaxReferences.FirstOrDefault();
                if (syntaxRef == null)
                {
                    continue;
                }

                var syntaxNode = syntaxRef.GetSyntax();

                var constructor = (syntaxNode as PropertyDeclarationSyntax)?.Initializer?.Value as ObjectCreationExpressionSyntax;
                if (constructor == null)
                {
                    continue;
                }

                var constructorArgumentLiteral = constructor.ArgumentList?.Arguments.FirstOrDefault()?.Expression as LiteralExpressionSyntax;
                if (constructorArgumentLiteral == null ||
                    !constructorArgumentLiteral.IsKind(SyntaxKind.StringLiteralExpression))
                {
                    continue;
                }

                result.Add((property.Name, constructorArgumentLiteral));
            }

            return result;
        }

        private static void Generate(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol> classSymbols)
        {
            foreach (var classSymbol in classSymbols)
            {
                var writer = new SourceWriter();
                writer.WriteLine("// <auto-generated/>");
                writer.WriteLine();
                writer.WriteLine("using System;");
                writer.WriteLine("using System.Collections.Generic;");
                writer.WriteLine();
                writer.WriteLine($"namespace {classSymbol.ContainingNamespace}");
                using (writer.BeginBlock())
                {
                    writer.WriteLine($"{classSymbol.DeclaredAccessibility.ToDisplayString()} partial class {classSymbol.Name}");
                    using (writer.BeginBlock())
                    {
                        writer.WriteLine($"private static readonly Dictionary<string, PdfName> lookup;");
                        writer.WriteLine();
                        writer.WriteLine($"static {classSymbol.Name}()");
                        using (writer.BeginBlock())
                        {
                            writer.WriteLine($"lookup = new(StringComparer.Ordinal)");
                            using (writer.BeginBlock(suffix: ";"))
                            {
                                var properties = GetNames(compilation, classSymbol);

                                foreach (var property in properties)
                                {
                                    writer.WriteLine($"{{ {property.Value.ToFullString()}, {property.PropertyName} }},");
                                }
                            }
                        }

                        writer.WriteLine();
                        writer.WriteLine($"public static bool TryLookup(string value, out PdfName result) => lookup.TryGetValue(value, out result);");
                    }
                }
                writer.WriteLine();

                context.AddSource(classSymbol.Name + ".g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
            }
        }
    }
}
